### PR TITLE
new validation + add serviceProvider + dependency injection + i18n

### PR DESCRIPTION
**Pull request by vkoori**
new validation + add serviceProvider + improve events + improve request + edit route config + block comments for cache + dependency injection + i18n

### CODE REVIEW

**Comment by lizhichao** [comment]
The current verifier is perfect enough that it is unnecessary to replace it.
file https://github.com/lizhichao/one/wiki/%E9%AA%8C%E8%AF%81%E5%99%A8

**Comment by lizhichao** [comment]
If you think the built-in rules are not enough, you can easily add them

**Comment by vkoori** [comment]
> If you think the built-in rules are not enough, you can easily add them

With current verifier we can use some rules similar to `required_with` or `required_if`

**Comment by vkoori** [comment]
> If you think the built-in rules are not enough, you can easily add them

With current

> If you think the built-in rules are not enough, you can easily add them

We cannot apply multiple rules together with the current validator. For example, if the input can be `null` or `string`, then we need to create a rule that checks these two conditions at the same time (`checkOne` method). - We are not allowed to use two separate rules to apply this condition (`nullable|string`). -

**Comment by lizhichao** [comment]
The minimalist validation provided by the framework has supported most scenarios.
If you have special scenarios that you do not support and do not want to add methods to support this function, you can introduce other packages into your project.

**Pull request closed without merging**
